### ISSUE TITLE
[Bug] Screenshot taking does not take correct place 

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#846] opened 2021-01-27 23:23 UTC
as of 75a99ae

MacOs version - 11.1 (latest)
Crome Version - 88.0.4324.96 (latest)
Firefox version - 85.0 (latest)

to reproduce:

0/ select any atlas
1/ Take a screenshot

expected behaviour: Screenshot picture should be selected place

actual behaviour: Screenshot picture is not a selected place

**Comment by xgui3783** [comment] 2021-01-28 08:31
cannot reproduce. see incl mp4. can you provide more details on the issue?

https://user-images.githubusercontent.com/19381783/106110895-9a0e4500-614b-11eb-9c76-1a70d104af45.mp4

**Comment by fsdavid** [comment] 2021-01-28 09:33
Strange in my PC both `localhost` and `dev-next` has an issues

**Comment by fsdavid** [comment] 2021-01-28 09:40
https://user-images.githubusercontent.com/26521731/106119219-39840580-6155-11eb-8d0b-2d37736b8372.mov

**Comment by xgui3783** [comment] 2021-01-28 10:09
welp, that's very interesting. 

can you report OS, chrome/FF version please?

**Comment by fsdavid** [comment] 2021-01-28 11:05
> can you report OS, chrome/FF version please?

Sure

**Comment by xgui3783** [comment] 2021-01-28 11:21
hmm, cannot reproduce in browser stack

I have 2 theories:
- somehow, when the bug occurs, the `HANDLE_SCREENSHOT_PROMISE` mistook the x, y starting point
- device pixel ratio

either way, can you try `capture whole screen` and let me know if that works properly?

**Comment by fsdavid** [comment] 2021-01-28 12:42
From the first look, it looks like the device pixel ratio. `capture whole screen` works well but capturing the whole screen with a selected area doesn't. I will assign the issue to myself and try to test the device pixel ratio (As I remember it was already considered but I could be wrong)

**Comment by fsdavid** [comment] 2021-01-28 12:43
I just saw you have assigned the issue you can look at it if you would like :)

**Comment by fsdavid** [comment] 2021-01-28 12:47
![image](https://user-images.githubusercontent.com/26521731/106140471-1e25f400-616f-11eb-9091-89aa70e53c61.png)
It looks half width and half height. As Mac has a retina display that has 2x pixels so it should be a pixel ratio issue.

**Comment by fsdavid** [comment] 2021-01-28 12:50
But it is already included into the code:
`this.croppedCanvas.width = this.boxEndWidth * window.devicePixelRatio`
`this.croppedCanvas.height = this.boxEndHeight * window.devicePixelRatio`

So the problem could be different

**Comment by xgui3783** [comment] 2021-01-28 13:08
bah macs... maybe we should stop support macs?

/joke

I think I may know where the issue reside. I will see if I can issue a patch

**Comment by xgui3783** [comment] 2021-01-28 13:18
can you pull and let me know if the issue persist?

**Comment by fsdavid** [comment] 2021-01-28 14:05
Yes, the issue is still there

**Comment by xgui3783** [comment] 2021-01-28 16:54
can you try the pull the latest commit from the same branch, and let me know if the issue has been resolved? commit should be 289eb222

Also, let me know if the screenshot is blurry.

**Comment by fsdavid** [comment] 2021-01-28 19:20
Now it is fixed

**Comment by xgui3783** [comment] 2021-01-29 08:36
fixed by #850

**Closed** 2021-01-29 08:35 UTC
Labels: bug
